from re import *
txt = "hello im python, im a programming language and bye"
# r = search("hello", txt)
# r = search("hello$", txt)
# r = search("bye$", txt)
# r = search("^hello", txt)
# r = search("^hello.bye$", txt)
# r = search("^hello.*bye$", txt)
# r = search("hello.*bye", txt)
# r = search("e$", txt)
# print(r)
# print(len(txt))
r = findall("hello", txt)
r = findall("^hello", txt)
r = findall("hello$", txt)
r = findall("hello.bye", txt)
r = findall("hello.*bye", txt)
r = findall(" ", txt)
print(r)